### ISSUE TITLE
Port # 6667 should be used for IRC Chat hook.

### ISSUE THREAD

**Issue by kotp** [marcric/roodle_lms#10]
Alternatively we can use CIA.vc but I think I would rather us the IRC hook.

**Comment by marcric** [comment]
Didn't get it. No label...

Is this one a planned, in progress or Invalid issue?

**Comment by kotp** [comment]
Sorry, was determining that, and clicked on save.  It is unplanned, I guess.  Actually, should have been re-open of prior issue.
Oops.

**Comment by marcric** [comment]
Do I need to take any action here?

**Comment by kotp** [comment]
Yes, please check the admin hooks, see if the port number is 6667.

**Comment by marcric** [comment]
Updated the port and the Room which was misspelled.

Here are the current settings: 

Server: irc.freenode.net 
Port: 6667 
Room: #Roodle_LMS 
Password:
Nick:
Ssl: not checked 
Long Url: not checked 
Active: checked

**Comment by kotp** [comment]
Yay!  It is working.
