### ISSUE TITLE
Use jquery instead of prototype

### ISSUE THREAD

**Issue by ugisozols** [marcric/roodle_lms#12]
Would this be ok with others to use jquery instead of prototype?

I already have the patch just wanted to hear some thoughts before sending pull request.

**Comment by marcric** [comment]
jQuery + 1

**Comment by ugisozols** [comment]
Use jquery instead of prototype. Closed by 5ecce80efa814284d4771259e30da0cd807297fc

**Comment by marcric** [comment]
marcric 42 minutes ago | link | edit | delete

I have seen the file changes and agree with them, now I need to find out how to commit that

(Just to keep a single issue for this)
