### ISSUE TITLE
Refactoring of OO-CSS support

### ISSUE THREAD

**Issue by marcric** [marcric/roodle_lms#13]
Unfortunately many Rails generators are based on weird CSS strategies.

Trying to adapt Rails generated code to fit oo-css will be a pain in the ass.

So, I will try to create a specific oo-css strategy requiring the minimum possible changes in the generated code.

**Comment by kotp** [comment]
Generators have changed with Rails 3.  Researching some things about them.  Also, we can create our own generators.

**Comment by marcric** [comment]
Some gems we will use have it's own generators... We can get in a loop.

**Comment by marcric** [comment]
Considering other tasks needs I will post pone this one for a further decision.
