### ISSUE TITLE
Get rid of Roodle Notes Wiki page

### ISSUE THREAD

**Issue by marcric** [marcric/roodle_lms#16]
Please someone get rid of the "Roodle Notes" Wiki page.

It is not used anymore and I don't know how to delete it.

**Comment by marcric** [comment]
Please, do the same for "Roodle Technical Notes" Wiki page.

It is not used anymore and I don't know how to delete it.

**Comment by kotp** [comment]
Completed.  These two pages are deleted.

Note: How to delete a wiki page.
- Edit the page
- Scroll down to bottom
- Click on "Delete this page"

**Comment by marcric** [comment]
Damn, it is a RED button, and I didn't see it...
