### ISSUE TITLE
I would like to have a beautiful Wiki home page in the future

### ISSUE THREAD

**Issue by marcric** [marcric/roodle_lms#20]
Hey Vic and Folks,

To be honest I prefer (partially), the old version of our Wiki home page.

I would like to get close to this one:

https://github.com/aslakhellesoy/cucumber/wiki

**Comment by marcric** [comment]
Transfered from the README issue goes on from here!

Good point ! But the link to C.C. license becomes broken.

And I noticed you get back to an intermediate format in the home page, but need to re-arrange the "Index of Roodle LMS Pages".

I suggest this one:
- About Roodle LMS Project
- Technical Notes (which will include the current "Testing the Application" page which in fact should be Running Tests).
- How to Install
- Testing the Application (a new one, which will show how users could test the application).

That is it.

**Comment by kotp** [comment]
Eventually, I would like to have the following installation choices:
- gem install roodle_lms
- Installation from repository
- Download from Git

**Comment by kotp** [comment]
License is updated, rather than simply re-linked.  Let me know if there are any changes to the license that is wanted.  (Or go to creative commons and select the preferred terms.)

Feel free to clone the wiki, and update and push.  Footer information is found in _Footer.md in the root.

**Comment by kotp** [comment]
See [Issue 7](https://github.com/marcric/roodle_lms/issues#issue/7/comment/620070) for backstory.

Part of that README.md ticket overflowed to here.

**Comment by marcric** [comment]
About installation choices, I have doubts:

Install it as a gem - will require another development strategy I think...

Developing a gem, is different from developing an application or I'm wrong?

Install it from repository - an outside github repository?

Download from git - we have currently two options: a tar or zip file and the git clone command. None of these?

**Comment by kotp** [comment]
Download from git, with a bin file that will help in running the 'initial setup steps' like bundle install && rake db:migrate  # Exact command depends on the OS.

As far as gem setup, no, you specify what you want to include, can include documentation and tests, or exclude documentation, up to the gem designer.  It is not that complex. I have built a couple of gems, previously.  But looking at how Bundler works, and we use it, take a look at this: [Creating and Publishing Your First Gem](http://blog.thepete.net/2010/11/creating-and-publishing-your-first-ruby.html) to see how simple it really can be.

Installing it from repository, would mean simply 'our' repository.  A How To document, basically on how to clone it and install it directly from the repository.

As far as Download "None of these?"  The answer is "Each of these!"  Just need to write up a "How To" with those steps as well.

**Comment by kotp** [comment]
"Just to clarify, you should check in your Gemfile.lock in applications, and not in gems. The Gemfile.lock remembers the exact versions and sources of every piece of third-party code that you use. For applications, you want this. When developing a gem, this can obscure issues that will occur because gems are deployed (using the gem command) without the benefit of bundler."  -- from Katz Got Your Tongue? by wycats

**Comment by marcric** [comment]
Mostly agreed.

I think we can (or must) postpone this task, because the project is in the early stages.

Unless we have to take any decision now to fit all the three options.

If that is the case, I suggest you to open a specific "installation decisions" issue.
