### ISSUE TITLE
Select a common data modeling tool

### ISSUE THREAD

**Issue by marcric** [marcric/roodle_lms#23]
One of the drawback I see in other projects is the lack of data modeling documentation.

Some times you need a great effort to understand how that specific model supports the application.

I suggest this one: http://code.google.com/p/wwwsqldesigner/

Reasoning:

It is platform independent: You just need a browser supporting Javascript.
It saves it's data in plain XML files.
It is simple (just what we need).

**Comment by kotp** [comment]
I noticed that it can also pull the structure from the existing database.

**Comment by marcric** [comment]
Yeah, it has some facilities (not explored yet), but I'm just focusing on a visual data modeling by now. To let us easily understand the intended relations and necessary fields.

For example, It just occurs me: a User should have a display name. In my case: my user name "marcric" should be displayed as "MarcRic".

**Comment by kotp** [comment]
Why such a specific return?  MarcRic is no way predictable from a programming perspective.  Unless you have other functionality, as in "How would you like your login displayed?" and an answer from the user.

The username should be case insensitive, and the expectations that we can know prior something as unpredictable as where to capitalize your letters properly, in this case, may be unreasonable.

**Comment by marcric** [comment]
I agree with your reasoning, but I have seen and used this facility somewhere else (I think it was in a local Rails discussion group).

My reasoning is: I always fill in the user account field with "marcric" I suppose they are always case insensitive, but if I had a chance, I would like it be displayed "MarcRic". Just because I like it more that way...

It could also be part of my full name which is "Marcos Ricardo Oliveira Souza", but could be better to just display "Marcos Ricardo".

Just one more field... We check for the user name field concerning authentication and authorization, but display the display name field which by default could be filled with the same user name content.

Didn't see any difficulty doing that way. I'm putting myself in a "User perspective".

I want it because I like it :-)

It is not that important anyway.

**Comment by kotp** [comment]
Well, I will say it isn't totally unpredictable, and the facility for making it work this way would be "Preferred Display Name" or something similar.  Will probably get implemented, I like it.  And it isn't 'totally' unpredictable, because matching parts of the name and capitalizing it based on logical guessing, is just an algorithm problem.

**Comment by marcric** [comment]
Oh man, I didn't make myself clear again...

There is no algorithm involved here, just one more field to be filled (or not) by the user when he submits the sign up form.

We will use the "user name" field to check on authentication and authorization, but always display the "display name" filed.

If the user leaves the "display name" field empty when signing up, we will fill it with the same value of the the "user name" field.

Very easy. If the user like he can use a display name like this "_-oOo-_", it is his decision.

Get it?

**Comment by kotp** [comment]
Yes, you were very clear.  I had just realized that your choice of capitalization wasn't as 'mysterious' to predict as I had made out.

But your solution is very practical, and is likely what we will use.

**Comment by marcric** [comment]
So, sqldesigner will be.
