### ISSUE TITLE
Testing rcov on our project in Windows

### ISSUE THREAD

**Issue by marcric** [marcric/roodle_lms#26]
I would like to know how to use rcov on our project.

One more item in the Testing application Wiki page.

I have read it is not yet full Ruby 1.9.2 compatible, and has Windows issues...

There is an alternative called "Cover me".

Have you seen this?

https://github.com/markbates/cover_me

**Comment by kotp** [comment]
What errors are you getting in Windows for rcov right now?

Try doing this:

``` console
rake spec:rcov
```

I looked it over, it would be usable.  For me, I am getting usable results from rcov.  At least for now.

**Comment by marcric** [comment]
Apparently it works...

http://twitpic.com/3mhzy2

http://twitpic.com/3mi023

http://twitpic.com/3mi06g

http://twitpic.com/3mi0a4

**Comment by kotp** [comment]
Better initial verification would be to open ./coverage/index.html

**Comment by marcric** [comment]
get it :-)

**Comment by kotp** [comment]
Unless we are determined to use cover_me I am closing this ticket.

**Comment by marcric** [comment]
I'm not able to to give an opinion.

Rcov is working fine on windows by now.

If you guys feel comfortable with rcov, rcov will be.
