### ISSUE TITLE
Set collaborator access for kotp

### ISSUE THREAD

**Issue by kotp** [marcric/roodle_lms#4]
Once ready for active development (and so Victor can edit the Wiki with Gollum)

**Comment by marcric** [comment]
Ha ha, so you cant update the Wiki but can create an Issue...

Interesting.

Let me just finish the Sign Up / Login task, and will add you.

**Comment by kotp** [comment]
Thanks.  Yeah, I can update the wiki on line, but have gollum installed and will be doing updates via that repository.

**Comment by kotp** [comment]
Access given.
