### ISSUE TITLE
Roodle photo link expired.

### ISSUE THREAD

**Issue by kotp** [marcric/roodle_lms#6]
Find better (more permanent example)

**Comment by marcric** [comment]
It is working for me...

Here is the location:

http://twitpic.com/3f21v1

But I want to display just the picture:

http://s3.amazonaws.com/twitpic/photos/full/206688493.jpg?AWSAccessKeyId=0ZRYP5X5F6FSMBCCSE82&Expires=1292148205&Signature=0sScJFrXpg2Ku4PsO%2Bi4GZ%2Fsdh8%3D

And this URL was shorted by: http://twtr.us/twtr.html

Which generates: http://tw0.us/R7u

And it was tested successfully few minutes ago.

Which is exactly the problem?

Ah may be the second link!

Ho Ho Ho, I'm waiting for a Christmas gift... I don' have any logo for the project right now!

**Comment by kotp** [comment]
Seems to be working for me today.  Server or routing issue last night.

Currently working on having the photo simply displayed in the wiki.
