### ISSUE TITLE
Improve the README.md file

### ISSUE THREAD

**Issue by marcric** [marcric/roodle_lms#7]
Put all the project information together and start thinking in a few basic decisions

**Comment by marcric** [comment]
- Will make the Roodle picture visible
- Will include a few more items in the file
- Will include an Authors section
- Will include a License section

**Comment by marcric** [comment]
BTW, which License will we use?

My vote goes for: Creative Commons

http://creativecommons.org/licenses/by-sa/3.0/us/

**Comment by marcric** [comment]
My work is done, waiting for more improvements / decisions

**Comment by kotp** [comment]
Working as well to make the graphic visible.  Not having too much luck.  But the photo is located as graphics/Roodle.jpg

**Comment by kotp** [comment]
kotp: Continue improvement of Readme file (and home wiki page) for grammer and LMS general statements.

**Comment by kotp** [comment]
Wiki page now comes up by default to list all pages.  Welcome page forced to be first.

Broken links removed from welcome page.

Graphic file moved to root directory, link changed accordingly.

**Comment by marcric** [comment]
Good point ! But the link to C.C. license becomes broken.

And I noticed you get back to an intermediate format in the home page, but need to re-arrange the "Index of Roodle LMS Pages".

I suggest this one:
- About Roodle LMS Project
- Technical Notes (which will include the current "Testing the Application" page which in fact should be Running Tests).

That is it.

(Transfered to [Issue 20](https://github.com/marcric/roodle_lms/issues/#issue/20) - MarcRic)

**Comment by marcric** [comment]
In the README file, we should include a "Releases" section, after the "Who is behind this project?" section, like this one:

# Releases
- Roodle 0.0.1 – Aaron Release (very first appearance), [Change Log](#)

**Comment by kotp** [comment]
Speaking of Release names... what would you like to theme them after?  Famous Breeders?  Famous dogs?

**Comment by marcric** [comment]
Since the name occurs me by a LMS smart as a Poodle and strong as a Rottweiler, I like the Famous dogs one:

http://www.google.com/search?q=famous+movie+dogs&ie=utf-8&oe=utf-8&aq=t&rls=org.mozilla:en-US:official&client=firefox-a
